AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hospedaria - reservas - DynamoDB reservas
Parameters:
  DynamoDbTableName:
    Description: Table Name
    Type: String
    Default: tbes_reservas
  Environment:
    Description: Environment
    Type: String
    Default: "dev"
  RCU:
    Description: Read Capacity Unit
    Type: String
    Default: "0"
  WCU:
    Description: Write Capacity Unit
    Type: String
    Default: "0"
  BillingMode:
    Description: Billing Mode
    Type: String
    Default: "PAY_PER_REQUEST"
  DeletionProtectionEnabled:
    Description: Deletion protection
    Type: String
    Default: "false"

Resources:
  ReservasDynamoDb:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
      - AttributeName: "id"
        AttributeType: "S"
      - AttributeName: "data"
        AttributeType: "S"
      - AttributeName: "nome"
        AttributeType: "S"
      - AttributeName: "email"
        AttributeType: "S"
      BillingMode: !Ref BillingMode
      DeletionProtectionEnabled: !Ref DeletionProtectionEnabled
      KeySchema: 
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "ix_data"
          KeySchema:
            - AttributeName: "data"
              KeyType: "HASH"
          ProvisionedThroughput: 
            ReadCapacityUnits: !Ref RCU
            WriteCapacityUnits: !Ref WCU
          Projection:
            ProjectionType: "ALL"
        - IndexName: "ix_nome"
          KeySchema:
            - AttributeName: "nome"
              KeyType: "HASH"
          ProvisionedThroughput: 
            ReadCapacityUnits: !Ref RCU
            WriteCapacityUnits: !Ref WCU
          Projection:
            ProjectionType: "ALL"
        - IndexName: "ix_email"
          KeySchema:
            - AttributeName: "email"
              KeyType: "HASH"
          ProvisionedThroughput: 
            ReadCapacityUnits: !Ref RCU
            WriteCapacityUnits: !Ref WCU
          Projection:
            ProjectionType: "ALL"
      ProvisionedThroughput: 
        ReadCapacityUnits: !Ref RCU
        WriteCapacityUnits: !Ref WCU
      TableName: !Ref DynamoDbTableName
      Tags: 
      - Key: Ambiente
        Value: !Ref Environment
      - Key: Microservico
        Value: Reservas